- 👋 Hi, I’m @Brasinha13.
- 👀 I’m interested in games I guess.
- 🌱 I’m currently learning coding.
- 💞️ I’m looking to collaborate on nothing, the school simply makes me do it.
- 📫 How to reach me, don't.
